/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlists;

public class App {
    
    public static void main(String[] args) {
        Vislink vl = new Vislink();
    }
}
